# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akRKl3nhkvpcmiBGdtQ8iUAgG-nXpPMy
"""

!pip install ultralytics
!pip install torchreid
!pip install git+https://github.com/KaiyangZhou/deep-person-reid.git
import numpy as np
import cv2
import os
import zipfile
import torch
from ultralytics import YOLO
from torchreid.utils import FeatureExtractor
from sklearn.neighbors import KNeighborsClassifier
from google.colab.patches import cv2_imshow

# --- 1. LOAD CUSTOM TRAINED DATA ---
def load_custom_model():
    print("Loading custom ResNet50 embeddings...")
    features = np.load('features.npy') # Shape: (37778, 2048)
    labels = np.load('labels.npy')     # Vehicle IDs
    paths = np.load('paths.npy')       # Paths

    # Path format fix for Colab/Linux
    paths = np.array([p.replace('\\', '/') for p in paths])

    # KNN for Metric Learning (using Cosine Similarity)
    # n_neighbors=1 kyunki humein exact match ya closest identity chahiye
    model = KNeighborsClassifier(n_neighbors=1, metric='cosine', algorithm='brute')
    model.fit(features, labels)

    print(f"Custom model trained on {features.shape[0]} samples with {features.shape[1]} dimensions.")
    return model, features, labels

# --- 2. EXTRACT REFERENCE DATA ---
def prepare_reference(zip_path):
    ref_folder = "reference_images"
    if not os.path.exists(ref_folder):
        print("Extracting Reference ZIP...")
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(ref_folder)
    return ref_folder

# --- 3. MAIN RE-ID PIPELINE ---
def run_resnet_reid():
    # 1. Models Setup
    knn_model, _, _ = load_custom_model()
    yolo = YOLO("yolov8n.pt")

    # IMPORTANT: Model name changed to resnet50 to match your 2048 dimensions
    print("Initializing ResNet50 Feature Extractor...")
    extractor = FeatureExtractor(
        model_name='resnet50',
        device='cuda' if torch.cuda.is_available() else 'cpu'
    )

    ref_folder = prepare_reference("Reference_image.zip")
    video_path = "vid_back.mp4"

    # 2. Extract Features for Reference Images (using ResNet50)
    print("Processing Reference Images...")
    reference_database = []
    for img_name in sorted(os.listdir(ref_folder)):
        img_path = os.path.join(ref_folder, img_name)
        img = cv2.imread(img_path)
        if img is not None:
            feat = extractor(img).flatten().cpu().numpy()
            reference_database.append(feat)

    # 3. Video Processing Setup
    cap = cv2.VideoCapture(video_path)
    w, h, fps = (int(cap.get(x)) for x in (3, 4, 5))
    out = cv2.VideoWriter('output_resnet_reid.mp4', cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))

    print("Starting Inference (30 seconds limit)...")
    frame_count = 0
    max_frames = 30 * fps # Approx 30 seconds

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret or frame_count > max_frames:
            break

        # Object Detection using YOLO
        results = yolo.track(frame, persist=True, classes=[2, 5, 7], verbose=False)

        if results[0].boxes.id is not None:
            boxes = results[0].boxes.xyxy.cpu().numpy()
            track_ids = results[0].boxes.id.cpu().numpy()

            for i, box in enumerate(boxes):
                x1, y1, x2, y2 = map(int, box)
                # Crop with padding check
                crop = frame[max(0,y1):min(h,y2), max(0,x1):min(w,x2)]

                if crop.size > 0:
                    # Feature extraction from video frame (ResNet50)
                    curr_feat = extractor(crop).flatten().cpu().numpy().reshape(1, -1)

                    # Search in Custom Trained Space
                    # dist is cosine distance (0 to 1, where 0 is identical)
                    dist, _ = knn_model.kneighbors(curr_feat)

                    # Threshold logic: 0.3 is strict for ResNet50
                    is_match = False
                    if dist[0][0] < 0.35:
                        # Double verify with Reference Images from ZIP
                        for r_feat in reference_database:
                            # Cosine Similarity check
                            cos_sim = np.dot(curr_feat, r_feat) / (np.linalg.norm(curr_feat) * np.linalg.norm(r_feat))
                            if cos_sim > 0.70: # 70% similarity threshold
                                is_match = True
                                break

                    # Visual Feedback
                    color = (0, 255, 0) if is_match else (0, 0, 255) # Green for match, Red for others
                    label = f"MATCH ID:{int(track_ids[i])}" if is_match else f"Car:{int(track_ids[i])}"
                    cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
                    cv2.putText(frame, label, (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        out.write(frame)

        # Monitor progress
        if frame_count % 100 == 0:
            print(f"Frame {frame_count}/{max_frames} processed...")
            # Display current frame result in Colab
            cv2_imshow(cv2.resize(frame, (640, 360)))

        frame_count += 1

    cap.release()
    out.release()
    print("--- SUCCESS! ---")
    print("Video saved as: output_resnet_reid.mp4")

if __name__ == "__main__":
    run_resnet_reid()
